// Code generated by Kitex v0.12.3. DO NOT EDIT.

package shorturlservice

import (
	shorturl "MicroService/kitex_gen/shorturl"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Generate(ctx context.Context, req *shorturl.GenerateReq, callOptions ...callopt.Option) (r *shorturl.GenerateResp, err error)
	Redirect(ctx context.Context, req *shorturl.RedirectReq, callOptions ...callopt.Option) (r *shorturl.RedirectResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kShortUrlServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kShortUrlServiceClient struct {
	*kClient
}

func (p *kShortUrlServiceClient) Generate(ctx context.Context, req *shorturl.GenerateReq, callOptions ...callopt.Option) (r *shorturl.GenerateResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Generate(ctx, req)
}

func (p *kShortUrlServiceClient) Redirect(ctx context.Context, req *shorturl.RedirectReq, callOptions ...callopt.Option) (r *shorturl.RedirectResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Redirect(ctx, req)
}
